# Generated by Django 3.1.7 on 2021-04-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0003_camps'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='detail',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
