# Generated by Django 3.1.7 on 2021-04-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0004_camps_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camps',
            name='detail',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
