# Generated by Django 3.1.7 on 2021-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0008_auto_20210406_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('designation', models.TextField(null=True)),
                ('image1', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
