# Generated by Django 3.1.7 on 2021-04-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0009_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='GALLERY_CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GALLERY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('nam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.gallery_category')),
            ],
        ),
    ]
