# Generated by Django 3.1.7 on 2021-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0010_gallery_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLOGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True)),
                ('Heading', models.TextField(max_length=30, null=True)),
                ('image1', models.FileField(null=True, upload_to='')),
                ('Detail', models.TextField(max_length=70, null=True)),
                ('Discription', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
