# Generated by Django 3.1.7 on 2021-04-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0011_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Detail',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
