# Generated by Django 3.1.7 on 2021-04-07 07:34

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0012_auto_20210407_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Discription',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
