# Generated by Django 3.1.7 on 2021-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0013_auto_20210407_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
