# Generated by Django 3.1.7 on 2021-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0014_blogs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='nam',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=30),
        ),
        migrations.DeleteModel(
            name='GALLERY_CATEGORY',
        ),
    ]
