# Generated by Django 3.1.7 on 2021-04-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0019_banner_about_banner_anantmandi_banner_camps_banner_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.blogs')),
            ],
        ),
    ]
