# Generated by Django 3.1.7 on 2021-04-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0020_blogimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='image1',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
