# Generated by Django 3.1.7 on 2021-04-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0023_campimages_pressimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campimages',
            name='pressimages',
        ),
    ]
