# Generated by Django 3.1.7 on 2021-04-09 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0027_gallery_campname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMPparticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('designation', models.TextField(null=True)),
                ('image1', models.FileField(null=True, upload_to='')),
                ('imag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.camps')),
            ],
        ),
        migrations.DeleteModel(
            name='CAMPimages',
        ),
    ]
