# Generated by Django 3.1.7 on 2021-04-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0028_auto_20210409_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campparticipants',
            name='designation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
