# Generated by Django 3.2 on 2021-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0031_oppurtunities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYMENT_PROCEDUREs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRIVACY_POLICYs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TERMS_CONDITIONSs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='oppurtunities',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
