# Generated by Django 3.2 on 2021-05-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0035_auto_20210428_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NEWS_LETTER',
        ),
    ]
