# Generated by Django 3.2 on 2021-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0036_delete_news_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS_LETTERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
