# Generated by Django 3.2 on 2021-05-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0037_news_letters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NEWS_LETTERS',
        ),
    ]
