# Generated by Django 3.2 on 2021-05-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0039_email_letters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_letters',
            old_name='email',
            new_name='mubmail',
        ),
    ]
