# Generated by Django 3.2 on 2021-05-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0037_news_letter'),
        ('zgoruban', '0040_rename_email_email_letters_mubmail'),
    ]

    operations = [
    ]
