# Generated by Django 3.2 on 2021-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0041_merge_20210516_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagess', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='NEWS_LETTER',
        ),
    ]
