# Generated by Django 3.2.4 on 2021-07-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0042_auto_20210518_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
    ]
